name: consultant_skills_operator
description: Operator workflow for managing consultant skills (setup-skills, teardown-skills, update-skills)
enabled: true
version: "1"

triggers:
  - type: manual

consts:
  api_base_url: https://sixth-cross-tel-newfoundland.trycloudflare.com

inputs:
  - name: operation
    type: string
    default: setup-skills
    description: "Operation to perform: setup-skills, teardown-skills, update-skills"
  - name: skills_path
    type: string
    default: ""
    description: "Optional path to skills directory (for update-skills operation)"

steps:
  - name: run_operation
    type: http
    with:
      url: "{{ consts.api_base_url }}/api/v1/ops/{{ inputs.operation }}"
      method: POST
      headers:
        Content-Type: application/json
      timeout: 120s
      body: >-
        {%- if inputs.skills_path != "" %}{"skills_path": "{{ inputs.skills_path }}"}{%- endif %}

  - name: final_result
    type: console
    with:
      message: |
        ============================================
        {{ inputs.operation | upcase }} - Complete
        ============================================
        Status: {{ steps.run_operation.output.data.status | default: '[MISSING]' }}
        Message: {{ steps.run_operation.output.data.message | default: '[MISSING]' }}
        {%- if steps.run_operation.output.data.details %}
        Details:
          Indexes: {{ steps.run_operation.output.data.details.indexes_created | default: steps.run_operation.output.data.details.indexes_deleted | join: ', ' }}
          Skills: {{ steps.run_operation.output.data.details.skills_created | default: steps.run_operation.output.data.details.skills_deleted | size }}
        {%- endif %}
        {%- if steps.run_operation.output.data.summary %}
        Summary: {{ steps.run_operation.output.data.summary }}
        {%- endif %}
        ============================================
